name: Quote workflow
on:
  push:
  schedule: # Run workflow automatically
    - cron: '0 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-quote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pull script to get quote
        uses: Kush-munot/quote-workflow@main
      - name: Commit and push changes
        run: |
          git config --global user.name "Kush-munot"
          git config --global user.email "munot.kgm@gmail.com"
          git add -A
          git commit -m "New Quote added"
          git push
